### ISSUE TITLE
Описание к скриптам

### ISSUE THREAD

**Issue by pihel** [xtender/xt_scripts#2]
Можно ли сделать html-ку с кратким описанием скриптов? Иначе достаточно сложно понять предназначение каждого, без их открытия.

**Comment by xtender** [comment]
Совсем кратенькое описание на русском я когда-то писал уже, но полноценно описать, поддерживать и расширять, к сожалению, нет времени: https://github.com/xtender/xt_scripts/blob/master/readme.ru.md
